config/routes.rb
Rails.application.routes.draw do
  #  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  #  resources :users, controller: "clearance/users", only: [:create] do
  #    resource :password,
  #      controller: "clearance/passwords",
  #      only: [:edit, :update]
  #  end

  get "/sign_in" => "clearance/sessions#new", :as => "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", :as => "sign_out"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # resources are protected
  constraints Clearance::Constraints::SignedIn.new do
    resources :menus
    resources :events, except: [:show, :index] do
      resources :pages
      resources :activities, except: [:show, :index]
    end

    resources :people, except: [:show]
  end

  # these are public

  resources :events, only: [:show, :index] do
    resources :activities, only: [:show, :index]
    resource :schedule, only: [:show]
  end

  get "/events/:event_id/teachers" => "people#facilitators"
  get "/teachers" => "people#facilitators"
  get "/events/:event_id/*slug" => "pages#show"
  resources :people, only: [:show]

  # uses "current" event
  get "/activities" => "activities#index"
  get "/classes" => "activities#index"
  get "/schedule" => "schedules#show"
  get "/*slug" => "pages#show"
  root "pages#show", defaults: {slug: "home"}

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :name, presence: true
  has_many :facilitations, dependent: :destroy
  has_many :activities, through: :facilitations

  scope :for_event, ->(event_id) do
    joins(:facilitations, :activities).where("activities.event_id" => event_id).distinct
  end

  def title
    name
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[show edit update destroy]

  def title_content
    content_for :title do
      @person.name
    end
  end

  def index
    @people = Person.all.order(:name)
    @heading = "All Teachers"
  end

  def facilitators
    @people = Person.for_event(@event).order(:name)
    @heading = "Teachers"

    render :index
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to [@person], notice: "Person was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    Person.find(params[:id])
    if @person.update(person_params)
      redirect_to [@person], notice: "Person was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @person.destroy!
    redirect_to people_path, notice: "Person was successfully destroyed.", status: :see_other
  end

  private

  def person_params
    params.expect(person: [:name, :bio])
  end

  def set_person
    @person = Person.find(params.expect(:id))
  end
end

app/views/people/_form.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.css">
<script src="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.js"></script>

<%= form_with model: [@person] do |form| %>
  <% if @person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% @person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>Use the name by which the person should be listed in the event program.
  This will usually be the SCA name. It should also include the title the
  person wishes to use.</p>
  <div class="mb-3">
  <%= form.label :name %>
  <%= form.text_field :name, class: "form-control" %>
  </div>

  <%= form.textarea :bio %>
  <%= form.submit class: "btn submit_button" %>
<% end %>

<script>
  const easyMDE = new EasyMDE();
</script>

app/views/people/edit.html.erb
<% title_from(@person) %>

<h1>Edit Person</h1>

<%= render "form", person: @person %>

<div>
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/index.html.erb
<% content_for :title, @heading %>
<h1><%= @heading %></h1>
<ul>
  <table class="index">
  <% @people.each do |person| %>
    <tr> 
      <td>• <%= link_to person.title, person %> </td>
      <% if signed_in? %>
        <td><%= button_to 'Edit', edit_person_path(person), method: :get, class: "btn submit_button" %></td>
      <% end %>
    </tr>
  <% end %>
  </table>
</ul>

<% if signed_in? %>
<%= button_to "New teacher", new_person_path, method: :get, class: "btn submit_button" %>
<% end %>

app/views/people/new.html.erb
<% content_for :title, "New person" %>

<h1>New Person</h1>

<%= render "form", person: @activity %>

<br>

<div>
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/show.html.erb
<% title_from(@person) %>

<h1><%= @person.name %></h1>

<% if @person.activities.any? %>
  <h2>Classes Taught</h2>
  <ul>
  <% @person.activities.each do |person| %>
    <li><%= link_to person.title, [person.event, person] %></li>
  <% end %>
  </ul>
<% end %>

<% if @person.bio.present? %>
  <h2>Biography</h2>
  <div class="details">
  <%== Kramdown::Document.new(@person.bio).to_html %>
  </div>
<% end %>

<% if signed_in? %>
  <div class="show_actions">
    <%= button_to 'Edit this person', edit_person_path(@person), method: :get, class: "btn submit_button" %>
  </div>
<% end %>