config/routes.rb
Rails.application.routes.draw do
  #  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  #  resources :users, controller: "clearance/users", only: [:create] do
  #    resource :password,
  #      controller: "clearance/passwords",
  #      only: [:edit, :update]
  #  end

  get "/sign_in" => "clearance/sessions#new", :as => "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", :as => "sign_out"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # resources are protected
  constraints Clearance::Constraints::SignedIn.new do
    resources :menus
    resources :events, except: [:show, :index] do
      resources :pages
      resources :activities, except: [:show, :index]
    end

    resources :people, except: [:show]
  end

  # these are public

  resources :events, only: [:show, :index] do
    resources :activities, only: [:show, :index]
    resource :schedule, only: [:show]
  end

  get "/events/:event_id/teachers" => "people#facilitators"
  get "/teachers" => "people#facilitators"
  get "/events/:event_id/*slug" => "pages#show"
  resources :people, only: [:show]

  # uses "current" event
  get "/activities" => "activities#index"
  get "/classes" => "activities#index"
  get "/schedule" => "schedules#show"
  get "/*slug" => "pages#show"
  root "pages#show", defaults: {slug: "home"}

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/pages/_form.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.css">
<script src="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.js"></script>

<%= form_with model: [@event, @page] do |form| %>
  <% if @page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% @page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
  <%= form.label :slug, style: "display: block" %>
  <%= form.text_field :slug, class: "form-control" %>
  </div>

  <div class="mb-3">
  <%= form.label :title, style: "display: block" %>
  <%= form.text_field :title, class: "form-control"%>
  </div>

  <%= form.textarea :body %>
  <%= form.submit class: "btn submit_button" %>
<% end %>

<script>
  const easyMDE = new EasyMDE();
</script>

app/views/pages/edit.html.erb
<% title_from(@page) %>

<h1>Edit page</h1>

<%= render "form", page: @page %>

<div>
  <%= link_to "Back to pages", event_pages_path(@event) %>
</div>

app/views/pages/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Pages" %>

<h1>Pages</h1>
<div id="pages">
  <table class="index">
    <tr>
      <th>Title</th>
      <th>Slug</th>
    </tr>

    <% @pages.each do |page| %>
      <tr>
        <td> <%= link_to page.title, [page.event, page] %> </td>
        <td> <tt><%= page.slug %></tt> </td>
        <td> <%= button_to 'Edit', edit_event_page_path(page.event, page), method: :get, class: "btn submit_button" %> </td>
        <td> <%= button_to 'Delete', [page.event, page], method: :delete, class: "btn btn-danger" %> </td>
      </tr>
    <% end %>
  </table>
</div>

<%= button_to "New page", new_event_page_path(@event), method: :get, class: "btn submit_button" %>

app/views/pages/new.html.erb
<% content_for :title, "New page" %>

<h1>New page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", event_pages_path(@event) %>
</div>

app/views/pages/show.html.erb
<% title_from(@page) %>

<h1><%= @page.title %></h1>

<%== Kramdown::Document.new(@page.body).to_html %>

<% if signed_in? %>
  <div class="show_actions">
    <%= button_to 'Edit this page', edit_event_page_path(@event,@page), method: :get, class: "btn submit_button" %>
    <%= button_to 'Delete this page', [@event, @page], method: :delete, class: "btn btn-danger" %>
  </div>
<% end %>