config/routes.rb
Rails.application.routes.draw do
  #  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  #  resources :users, controller: "clearance/users", only: [:create] do
  #    resource :password,
  #      controller: "clearance/passwords",
  #      only: [:edit, :update]
  #  end

  get "/sign_in" => "clearance/sessions#new", :as => "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", :as => "sign_out"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # resources are protected
  constraints Clearance::Constraints::SignedIn.new do
    resources :menus
    resources :events, except: [:show, :index] do
      resources :pages
      resources :activities, except: [:show, :index]
    end

    resources :people, except: [:show]
  end

  # these are public

  resources :events, only: [:show, :index] do
    resources :activities, only: [:show, :index]
    resource :schedule, only: [:show]
  end

  get "/events/:event_id/teachers" => "people#facilitators"
  get "/teachers" => "people#facilitators"
  get "/events/:event_id/*slug" => "pages#show"
  resources :people, only: [:show]

  # uses "current" event
  get "/activities" => "activities#index"
  get "/classes" => "activities#index"
  get "/schedule" => "schedules#show"
  get "/*slug" => "pages#show"
  root "pages#show", defaults: {slug: "home"}

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  # DEPRECATED FIELDS -- should use ScheduleEntry: classroom, start_time
  #
  belongs_to :difficulty, optional: true
  belongs_to :event
  belongs_to :activity_type, optional: true
  belongs_to :activity_subtype, optional: true
  has_many :facilitations, dependent: :destroy
  has_many :facilitators, source: :person, through: :facilitations

  validates :title, presence: true
  validates :duration, presence: true
end

app/models/activity_type.rb
class ActivityType < ActiveRecord::Base
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[show edit update destroy]

  def title_content
    content_for :title do
      @activity.title
    end
  end

  def index
    @activities = event.activities
    @heading = "Classes"
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)
    if @activity.save
      redirect_to [event, @activity], notice: "Activity was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @activity.update(activity_params)
      redirect_to [event, @activity], notice: "Activity was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @activity.destroy!
    redirect_to event_activities_path(event), notice: "Activity was successfully destroyed.", status: :see_other
  end

  private

  def activity_params
    params.expect(
      activity: [
        :title,
        :duration,
        :description,
        :classroom_id,
        :activity_type_id,
        :activity_subtype_id,
        :difficulty_id,
        facilitator_ids: []
      ]
    ).merge(event: event)
  end

  def set_activity
    @activity = Activity.find_by!(event: event, id: params.expect(:id))
  end
end

app/views/activities/_form.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.css">
<script src="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/use-bootstrap-select@2.2.1/dist/use-bootstrap-select.min.css">
<script src="https://cdn.jsdelivr.net/npm/use-bootstrap-select@2.2.1/dist/use-bootstrap-select.min.js"></script>

<%= form_with model: [@event, @activity] do |form| %>
  <% if @activity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% @activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
  <%= form.label :title %>
  <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
  <%= form.label "Teachers" %>
    <%= form.collection_select :facilitator_ids, Person.order(:name), :id, :name, {},{class: "form-select", data: {searchable: true}, multiple: true} %>
  </div>

  <div class="mb-3">
  <%= form.label :duration %>
  <%= form.text_field :duration, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description %>
    <%= form.textarea :description %>
  </div>
  <%= form.submit class: "btn submit_button"%>
<% end %>

<script>
  const easyMDE = new EasyMDE();
  new UseBootstrapSelect(document.getElementById('activity_facilitator_ids'));
</script>

app/views/activities/edit.html.erb
<% title_from(@activity) %>

<h1>Edit activity</h1>

<%= render "form", activity: @activity %>

<div>
  <%= link_to "Back to activities", event_activities_path(@event) %>
</div>

app/views/activities/index.html.erb
<% content_for :title, @heading %>
<h1><%=@heading%> for <%= @event.title %></h1>
<ul>
  <table class="index">
      <tr>
        <th>Title</th>
        <th>Teacher(s)</th>
      </tr>
    <% @activities.each do |activity| %>
      <tr> 
        <td>
          <%= link_to activity.title, [activity.event, activity] %>
        </td>
        <td>
          <%= activity.facilitators.map(&:name).join(", ") %>
        </td>
        <% if signed_in? %>
          <td><%= button_to 'Edit', edit_event_activity_path(activity.event, activity), method: :get, class: "btn submit_button" %></td>
          <td><%= button_to 'Delete', [activity.event, activity], method: :delete, class: "btn btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
</ul>

<% if signed_in? %>
  <%= button_to "New class", new_event_activity_path(@event), method: :get, class: "btn submit_button" %>
<% end %>

app/views/activities/new.html.erb
<% content_for :title, "New activity" %>

<h1>New Activity</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Back to activities", event_activities_path(@event) %>
</div>

app/views/activities/show.html.erb
<% title_from(@activity) %>

<h1><%= @activity.title %></h1>

<% @activity.facilitators.each do |person| %>
  <h2 class="people_names"><%= link_to person.name, person %></h2>
<% end %>

<div class="details">
<%== Kramdown::Document.new(@activity.description).to_html %>
</div>

<% if signed_in? %>
  <div class="show_actions">
    <%= button_to 'Edit this activity', edit_event_activity_path(@event,@activity), method: :get, class: "btn submit_button" %>
    <%= button_to 'Delete this activity', [@event, @activity], method: :delete, class: "btn btn-danger" %>
  </div>
<% end %>