config/routes.rb
Rails.application.routes.draw do
  #  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  #  resources :users, controller: "clearance/users", only: [:create] do
  #    resource :password,
  #      controller: "clearance/passwords",
  #      only: [:edit, :update]
  #  end

  get "/sign_in" => "clearance/sessions#new", :as => "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", :as => "sign_out"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # resources are protected
  constraints Clearance::Constraints::SignedIn.new do
    resources :menus
    resources :events, except: [:show, :index] do
      resources :pages
      resources :activities, except: [:show, :index]
    end

    resources :people, except: [:show]
  end

  # these are public

  resources :events, only: [:show, :index] do
    resources :activities, only: [:show, :index]
    resource :schedule, only: [:show]
  end

  get "/events/:event_id/teachers" => "people#facilitators"
  get "/teachers" => "people#facilitators"
  get "/events/:event_id/*slug" => "pages#show"
  resources :people, only: [:show]

  # uses "current" event
  get "/activities" => "activities#index"
  get "/classes" => "activities#index"
  get "/schedule" => "schedules#show"
  get "/*slug" => "pages#show"
  root "pages#show", defaults: {slug: "home"}

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller

  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  before_action :set_event

  allow_browser versions: :modern

  def set_event
    @event = if params[:event_id]
      Event.find(params[:event_id])
    else
      Event.current
    end
  end

  attr_reader :event
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Hardcoded for now; could vary by event in the future
  EVENT_SERIES = "St. Cecilia at the Tower"

  def title_from(thing)
    content_for :title, thing.title
  end

  def title
    content = content_for(:title)
    if content
      "#{content} - #{EVENT_SERIES}"
    else
      EVENT_SERIES
    end
  end

  def alert_class(type)
    case type
    when "alert"
      "alert-danger"
    when "notice"
      "alert-success"
    else
      type
    end
  end
end

app/views/application/_menu.html.erb
<nav class="navbar navbar-expand-md" style="background-color: #bf281d" aria-label="Menu" role="navigation" >

  <div class="container container-fluid">
    <p class="navbar-brand d-block d-md-none" href="#"><%= @event.title %></p>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-md-center" id="navbarNav">
      <ul class="navbar-nav ">
        <li class="nav-item"><%= link_to "Home", "/", class: ["nav-link"] %>
        <% MenuItem.where(event: @event).order(:order).each do |menu_item| %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false"><%= menu_item.name %></a>
            <ul class="dropdown-menu">
              <% Page.where(menu_item: menu_item).order(:menu_order).each do |page| %>
                <li><%= link_to page.title, "/" + page.slug, class: ["dropdown-item"] %></li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/application/_top_menu.html.erb
<nav class="navbar navbar-expand-md" style="background-color: #bf281d" aria-label="Menu" role="navigation" >

  <div class="container container-fluid">
    <p class="navbar-brand d-block d-md-none" href="#"><%= @event.short_name || @event.title %></p>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-md-center" id="navbarNav">
      <ul class="navbar-nav ">
        <li class="nav-item"><%= link_to "Home", "/", class: ["nav-link"] %>
        <% Menu.where(event: @event).order(:order).each do |menu| %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false"><%= menu.name %></a>
            <ul class="dropdown-menu">
              <% menu.menu_items.order(:order).each do |menu_item| %>
                <li><%= link_to menu_item.name, menu_item.url, class: ["dropdown-item"] %></li>
              <% end %>
            </ul>
          </li>
        <% end %>
        <% if signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Admin</a>
            <ul class="dropdown-menu">
                <li><%= link_to "Manage Pages", event_pages_url(@event), class: ["dropdown-item"] %></li>
                <li><%= link_to "Manage Classes", event_activities_url(@event), class: ["dropdown-item"] %></li>
                <li><%= link_to "Manage Teachers", people_url, class: ["dropdown-item"] %></li>
                <li><%= button_to "Sign out", sign_out_path, method: :delete, class: ["dropdown-item"] %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>